#!/bin/sh
if [ $# -eq 0 ]; then
    file=noobs.zip
else
    file=$1
fi

umount /mnt
mount /dev/mmcblk0p1 /mnt
wget updates.fiveninjas.com/slice/$file
wget updates.fiveninjas.com/slice/$file.md5
md5sum -c $file.md5
if [ $? -eq 0 ]; then
  unzip $file -o -d /mnt
else
  echo Failed to download $file, MD5 sum check failed
fi
mount /mnt -o remount,ro
